version: '3'

services:
        springboot:
                container_name: springboot
                build:
                        context: /opt/jenkins/workspace/BE/backend
                ports:
                        - "8080:8080"
        react:
                container_name: react
                build:
                        context: /opt/jenkins/workspace/FE/frontend
                ports:
                        - "3000:3000"
        nginx:
                image: nginx
                container_name: nginx
                volumes:
                        - /opt/nginx/conf.d:/etc/nginx/conf.d
                        - /opt/certbot/conf:/etc/letsencrypt
                        - /opt/certbot/www:/var/www/certbot
                ports:
                        - "80:80"
                        - "443:443"
        certbot:
                image: certbot/certbot
                container_name: certbot
                volumes:
                         - /opt/certbot/conf:/etc/letsencrypt
                         - /opt/certbot/www:/var/www/certbot
