import { Flower } from "./Flower";

export const flowerList: Flower[] = [
  {
    flowerSeq: 1,
    flowerName: "장미",
    flowerColor: "red",
    flowerImage: "/img/roseRed.png",
    flowerDesc: "불타는 사랑",
  },
  {
    flowerSeq: 2,
    flowerName: "장미",
    flowerColor: "Orange",
    flowerImage: "/img/roseOrange.png",
    flowerDesc: "불타는 사랑",
  },
  {
    flowerSeq: 3,
    flowerName: "장미",
    flowerColor: "Pink",
    flowerImage: "/img/rosePink.png",
    flowerDesc: "불타는 사랑",
  },
  {
    flowerSeq: 4,
    flowerName: "장미",
    flowerColor: "red",
    flowerImage: "/img/roseWhite.png",
    flowerDesc: "불타는 사랑",
  },
  {
    flowerSeq: 5,
    flowerName: "튤립",
    flowerColor: "red",
    flowerImage: "/img/tulipPurple.png",
    flowerDesc: "불타는 사랑",
  },
  {
    flowerSeq: 6,
    flowerName: "튤립",
    flowerColor: "red",
    flowerImage: "/img/tulipPink.png",
    flowerDesc: "불타는 사랑",
  },
  {
    flowerSeq: 7,
    flowerName: "튤립",
    flowerColor: "red",
    flowerImage: "/img/tulipRed.png",
    flowerDesc: "불타는 사랑",
  },
  {
    flowerSeq: 8,
    flowerName: "튤립",
    flowerColor: "red",
    flowerImage: "/img/tulipYellow.png",
    flowerDesc: "불타는 사랑",
  },
  {
    flowerSeq: 9,
    flowerName: "카네이션",
    flowerColor: "red",
    flowerImage: `/img/carnationRed.png`,
    flowerDesc: "불타는 사랑",
  },
  {
    flowerSeq: 10,
    flowerName: "카네이션",
    flowerColor: "red",
    flowerImage: `/img/carnationOrange.png`,
    flowerDesc: "불타는 사랑",
  },
  {
    flowerSeq: 11,
    flowerName: "카네이션",
    flowerColor: "red",
    flowerImage: `/img/carnationPink.png`,
    flowerDesc: "불타는 사랑",
  },
  {
    flowerSeq: 12,
    flowerName: "카네이션",
    flowerColor: "red",
    flowerImage: `/img/carnationYellow.png`,
    flowerDesc: "불타는 사랑",
  },
  {
    flowerSeq: 13,
    flowerName: "프리지아",
    flowerColor: "red",
    flowerImage: `/img/freesiaPink.png`,
    flowerDesc: "불타는 사랑",
  },
  {
    flowerSeq: 14,
    flowerName: "프리지아",
    flowerColor: "red",
    flowerImage: `/img/freesiaPurple.png`,
    flowerDesc: "불타는 사랑",
  },
  {
    flowerSeq: 15,
    flowerName: "프리지아",
    flowerColor: "red",
    flowerImage: `/img/freesiaYellow.png`,
    flowerDesc: "불타는 사랑",
  },
];

export const flowerColor = ["red", "yellow", "pink", "purple"];
