import { FlowerType } from "./Flower";

export const flowerList: FlowerType[] = [
  {
    flowerSeq: 4,
    flowerName: "거베라",
    flowerColor: "red",
    flowerImage: "/img/gerberaYellow.png",
    flowerDesc: "불타는 사랑",
  },
  {
    flowerSeq: 5,
    flowerName: "장미",
    flowerColor: "Orange",
    flowerImage: "/img/gerberaPink.png",
    flowerDesc: "불타는 사랑",
  },
  {
    flowerSeq: 6,
    flowerName: "장미",
    flowerColor: "Pink",
    flowerImage: "/img/gerberaOrange.png",
    flowerDesc: "불타는 사랑",
  },
  {
    flowerSeq: 7,
    flowerName: "라넌큘러스",
    flowerColor: "red",
    flowerImage: "/img/ranunculusYellow.png",
    flowerDesc: "불타는 사랑",
  },
  {
    flowerSeq: 8,
    flowerName: "라넌큘러스",
    flowerColor: "red",
    flowerImage: "/img/ranunculusPurple.png",
    flowerDesc: "불타는 사랑",
  },
  {
    flowerSeq: 9,
    flowerName: "라넌큘러스",
    flowerColor: "red",
    flowerImage: "/img/ranunculusPink.png",
    flowerDesc: "불타는 사랑",
  },
  {
    flowerSeq: 10,
    flowerName: "리시안셔스",
    flowerColor: "red",
    flowerImage: "/img/lisianthusPink.png",
    flowerDesc: "불타는 사랑",
  },
  {
    flowerSeq: 11,
    flowerName: "리시안셔스",
    flowerColor: "red",
    flowerImage: "/img/lisianthusPurple.png",
    flowerDesc: "불타는 사랑",
  },
  {
    flowerSeq: 12,
    flowerName: "리시안셔스",
    flowerColor: "red",
    flowerImage: `/img/lisianthusWhite.png`,
    flowerDesc: "불타는 사랑",
  },
  {
    flowerSeq: 13,
    flowerName: "백합",
    flowerColor: "red",
    flowerImage: `/img/lilyYellow.png`,
    flowerDesc: "불타는 사랑",
  },
  {
    flowerSeq: 14,
    flowerName: "백합",
    flowerColor: "red",
    flowerImage: `/img/lilyPink.png`,
    flowerDesc: "불타는 사랑",
  },
  {
    flowerSeq: 15,
    flowerName: "백합",
    flowerColor: "red",
    flowerImage: `/img/lilyWhite.png`,
    flowerDesc: "불타는 사랑",
  },
  {
    flowerSeq: 16,
    flowerName: "수국",
    flowerColor: "red",
    flowerImage: `/img/hydrangeaPurple.png`,
    flowerDesc: "불타는 사랑",
  },
  {
    flowerSeq: 17,
    flowerName: "수국",
    flowerColor: "red",
    flowerImage: `/img/hydrangeaPink.png`,
    flowerDesc: "불타는 사랑",
  },
  {
    flowerSeq: 18,
    flowerName: "수국",
    flowerColor: "red",
    flowerImage: `/img/hydrangeaBlue.png`,
    flowerDesc: "불타는 사랑",
  },
  {
    flowerSeq: 19,
    flowerName: "작약",
    flowerColor: "red",
    flowerImage: `/img/peonyPink.png`,
    flowerDesc: "불타는 사랑",
  },
  {
    flowerSeq: 20,
    flowerName: "작약",
    flowerColor: "red",
    flowerImage: `/img/peonyRed.png`,
    flowerDesc: "불타는 사랑",
  },
  {
    flowerSeq: 21,
    flowerName: "작약",
    flowerColor: "red",
    flowerImage: `/img/peonyWhite.png`,
    flowerDesc: "불타는 사랑",
  },
  {
    flowerSeq: 22,
    flowerName: "장미",
    flowerColor: "red",
    flowerImage: `/img/rosePink.png`,
    flowerDesc: "불타는 사랑",
  },
  {
    flowerSeq: 23,
    flowerName: "장미",
    flowerColor: "red",
    flowerImage: `/img/roseRed.png`,
    flowerDesc: "불타는 사랑",
  },
  {
    flowerSeq: 24,
    flowerName: "장미",
    flowerColor: "red",
    flowerImage: `/img/roseOrange.png`,
    flowerDesc: "불타는 사랑",
  },
  {
    flowerSeq: 25,
    flowerName: "장미",
    flowerColor: "red",
    flowerImage: `/img/roseWhite.png`,
    flowerDesc: "불타는 사랑",
  },
  {
    flowerSeq: 26,
    flowerName: "카네이션",
    flowerColor: "red",
    flowerImage: `/img/carnationYellow.png`,
    flowerDesc: "불타는 사랑",
  },
  {
    flowerSeq: 27,
    flowerName: "카네이션",
    flowerColor: "red",
    flowerImage: `/img/carnationPink.png`,
    flowerDesc: "불타는 사랑",
  },
  {
    flowerSeq: 28,
    flowerName: "카네이션",
    flowerColor: "red",
    flowerImage: `/img/carnationRed.png`,
    flowerDesc: "불타는 사랑",
  },
  {
    flowerSeq: 29,
    flowerName: "카네이션",
    flowerColor: "red",
    flowerImage: `/img/carnationOrange.png`,
    flowerDesc: "불타는 사랑",
  },
  {
    flowerSeq: 30,
    flowerName: "튤립",
    flowerColor: "red",
    flowerImage: `/img/tulipYellow.png`,
    flowerDesc: "불타는 사랑",
  },
  {
    flowerSeq: 31,
    flowerName: "튤립",
    flowerColor: "red",
    flowerImage: `/img/tulipPurple.png`,
    flowerDesc: "불타는 사랑",
  },
  {
    flowerSeq: 32,
    flowerName: "튤립",
    flowerColor: "red",
    flowerImage: `/img/tulipPink.png`,
    flowerDesc: "불타는 사랑",
  },
  {
    flowerSeq: 33,
    flowerName: "튤립",
    flowerColor: "red",
    flowerImage: `/img/tulipRed.png`,
    flowerDesc: "불타는 사랑",
  },
  {
    flowerSeq: 34,
    flowerName: "프리지아",
    flowerColor: "red",
    flowerImage: `/img/freesiaYellow.png`,
    flowerDesc: "불타는 사랑",
  },
  {
    flowerSeq: 35,
    flowerName: "프리지아",
    flowerColor: "red",
    flowerImage: `/img/freesiaPurple.png`,
    flowerDesc: "불타는 사랑",
  },
  {
    flowerSeq: 36,
    flowerName: "프리지아",
    flowerColor: "red",
    flowerImage: `/img/freesiaPink.png`,
    flowerDesc: "불타는 사랑",
  },
  {
    flowerSeq: 37,
    flowerName: "해바라기",
    flowerColor: "red",
    flowerImage: `/img/sunflowerYellow.png`,
    flowerDesc: "불타는 사랑",
  },
  {
    flowerSeq: 38,
    flowerName: "히아신스",
    flowerColor: "red",
    flowerImage: `/img/hyacinthYellow.png`,
    flowerDesc: "불타는 사랑",
  },
  {
    flowerSeq: 39,
    flowerName: "히아신스",
    flowerColor: "red",
    flowerImage: `/img/hyacinthPurple.png`,
    flowerDesc: "불타는 사랑",
  },
  {
    flowerSeq: 40,
    flowerName: "히아신스",
    flowerColor: "red",
    flowerImage: `/img/hyacinthPink.png`,
    flowerDesc: "불타는 사랑",
  },
];

export const flowerColor = ["red", "yellow", "pink", "purple"];
